<?php

/**
 * @file
 * Install functions for the Wysiwyg Fields tests module.
 */

/**
 * Implements hook_install().
 */
function wysiwyg_fields_test_install() {
  node_types_rebuild();
  $types = node_type_get_types();

  node_add_body_field($types['wysiwyg_fields_test']);
}

/**
 * Implements hook_uninstall().
 */
function wysiwyg_fields_test_uninstall() {
  $nodes = node_load_multiple(array(), array('type' => 'wysiwyg_fields_test'));
  node_delete_multiple(array_keys($nodes));
  node_type_delete('wysiwyg_fields_test');
}
